version: '3.1'
services:
    db:
        image: docker.io/debezium/postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: insights
            POSTGRES_USER: insights
            POSTGRES_DB: insights
        ports:
            - 5432:5432
    hsp:
        build: .
        ports:
            - 8080:8080
        links:
            - db
        depends_on:
            - db
