"""removed modified_on column

Revision ID: e6ce6eb6ba32
Revises: 6c97901967f3
Create Date: 2020-04-23 17:37:44.607724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e6ce6eb6ba32"
down_revision = "6c97901967f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("historical_system_profiles", "modified_on")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_system_profiles",
        sa.Column(
            "modified_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
